# Generated by Django 4.2.14 on 2024-07-15 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_product_image_alter_product_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='passwrod',
            new_name='password',
        ),
        migrations.AddField(
            model_name='categories',
            name='is_electronics',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ElectronicProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen', models.CharField(max_length=30)),
                ('ram', models.CharField(max_length=15)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='electronic_features', to='shop.product')),
            ],
        ),
    ]
