# Generated by Django 4.2.14 on 2024-07-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_passwrod_customer_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicproduct',
            name='ram',
            field=models.CharField(choices=[('2GB', '2GB'), ('4GB', '4GB'), ('8GB', '8GB'), ('16GB', '16GB')], max_length=15),
        ),
        migrations.AlterField(
            model_name='electronicproduct',
            name='screen',
            field=models.CharField(choices=[('LCD', 'LCD'), ('LED', 'LED'), ('OLED', 'OLED'), ('AMOLED', 'AMOLED')], max_length=30),
        ),
    ]
